site_name: CCALL DOCS
site_description:  Tổng đài CCALL Cloud Doanh nghiệp: Hướng dẫn sử dụng, Quản trị và Phát triển
theme: readthedocs
pages:
    - 'Hướng dẫn sử dụng CCALL Softphone': 'huong-dan-su-dung-ccall-softphone.md'
    - 'Hướng dẫn lắp đặt điện thoại Fanvil': 'huong-dan-lap-dat-dien-thoai-fanvil.md'
    - 'Hướng dẫn cấu hình điện thoại Fanvil': 'huong-dan-cau-hinh-dien-thoai-fanvil.md'
    - 'Hướng dẫn tích hợp lấy CDR, ghi âm, máy nhánh online': 'huong-dan-tich-hop.md'
